name: Build Electron Apps

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install electron-packager
        run: npm install --save-dev electron-packager

      - name: Build Windows app
        run: |
          echo "Starting build"
          npx electron-packager . SuperVibeyGraphicsEditor --overwrite --platform=win32 --arch=x64 --icon=assets/app-icon.ico --out=dist
          echo "Build finished"
          ls -l dist

      - name: Zip Windows build
        run: |
          cd dist
          zip -r SuperVibeyGraphicsEditor-windows-x64.zip SuperVibeyGraphicsEditor-win32-x64

      - name: Upload Windows zip to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-x64:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install electron-packager
        run: npm install --save-dev electron-packager

      - name: Build macOS x64 app
        run: |
          echo "Starting build (x64)"
          npx electron-packager . SuperVibeyGraphicsEditor --overwrite --platform=darwin --arch=x64 --icon=assets/app-icon.icns --out=dist
          echo "Build finished"
          ls -l dist

      - name: Zip macOS x64 build
        run: |
          cd dist
          zip -r SuperVibeyGraphicsEditor-macos-x64.zip SuperVibeyGraphicsEditor-darwin-x64

      - name: Upload macOS x64 zip to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install electron-packager
        run: npm install --save-dev electron-packager

      - name: Build macOS arm64 app
        run: |
          echo "Starting build (arm64)"
          npx electron-packager . SuperVibeyGraphicsEditor --overwrite --platform=darwin --arch=arm64 --icon=assets/app-icon.icns --out=dist
          echo "Build finished"
          ls -l dist

      - name: Zip macOS arm64 build
        run: |
          cd dist
          zip -r SuperVibeyGraphicsEditor-macos-arm64.zip SuperVibeyGraphicsEditor-darwin-arm64

      - name: Upload macOS arm64 zip to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
